### ISSUE TITLE
Prevent admins from auctioning other players' claims

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#15]
- Permissions are kept when an auction fails to be created. Great!
- "Sign was placed in subclaim, canceling auction creation." Great!
- Non-owners cannot create an auction when they are trusted on the claim. Great!
- Non-OP cannot auction Admin claims. Great!
- OP can auction Admin claims. Great!

I don't know if it's possible but, how about blocking OP from creating auctions on other player's claims? I am mistake prone.

What did I forget to test?

**Comment by RoboMWM** [comment]
I use `griefprevention.adminclaims` permission. I don't know if it's possible to test for the /ignoreclaims permission for other claims without also allowing those with trust to auction off a claim.

But it sounds like you want to prevent others from auctioning another person's claim, no matter the permission hierarchy. If that's so I can do that, and then only check the permission for admin claims.

**Comment by NullCase** [comment]
confirmed this is working.
