### ISSUE TITLE
Displaying auction info

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#17]
Hi @RoboMWM It seems like you may decide to split this into 2 issues. That's ok by me.

1) when an auction is created, **update the sign** to display the following auction information:

[Real Estate]
&2Auction
Player's Name
Next Bid Price (unformated)

2) Shift + right clicking the sign **displays auction information**.

&9----= &f[&6RealEstate Auction Info&f]&9=----
&bThis &aCLAIM &bis on auction for &a[next bid price]
&bThe auction closes in &a[remaining time in hours] &bhours.
&bThe current/previous owner is: &a[players name]
&bThe most recent bidder is: &a[last bidder] **OR** No Bidders.

_Use previous owner for automated auctions (later)_
Use current owner for voluntary auctions.
Use No Bidders if no bidders, otherwise last bidder.

These items take care of this section (posted this mainly for my benefit).
https://github.com/NullCase/GPRealEstate/issues/1#issuecomment-459858952

**Comment by RoboMWM** [comment]
Hmm, I think the sign might not be updated on creation because I don't cancel the sign edit event.

**Comment by NullCase** [comment]
It sounds like you use the sign edit event rather than canceling it?

I have no idea how to code, still here's one suggestion.

What about checking GPRealEstate? Because Pyro must have done something similar to update his signs on creation.

**Comment by RoboMWM** [comment]
I monitor sign edit to see when someone actually submits text on the sign. I do all the update code and etc., but I forgot that the sign edit event will just overwrite whatever I update the sign to since I'm technically doing it before the sign edit is applied. So all I need to do is cancel the event.

**Comment by NullCase** [comment]
It looks like you've got it sorted then?

**Comment by NullCase** [comment]
Will test tomorrow!

**Comment by NullCase** [comment]
I'm sorry, it looks like something trivial was overlooked while testing.

Presently shift + clicking looks like this
![2019-02-18_17 31 37](https://user-images.githubusercontent.com/32785664/52979335-12d2c700-33a3-11e9-9499-71649fb8487f.png)

It looks like my "hours" part is redundant.

Instead how about we use this one:
&bThe auction closes in &a[remaining time]&b.
