### ISSUE TITLE
Creating bids (during auction)

### ISSUE THREAD

**Issue by RoboMWM** [RoboMWM/GPAuctions#2]
- [x] Next bid is configurable increment of prior bid (@Nullcase wants it percentage-based instead of global fixed value - assuming percentage based off of last bid, or fixed off of starting price only?)

- [x] Right-click sign
  - [x] Verify bidder balance

- [x] Message the player.

[&6GPAuctions&f] &bYour bid of &a[bid price] &bhas been accepted. If you are the Auction winner payment will be due in &a[remaining time in hours] &bhours.

_Or_

[&6GPAuctions&f] &bYou have insufficient funds to place a bid at this time.

- [x] Update sign after successful bid

**Comment by NullCase** [comment]
percentage based off of last bid.

**Comment by RoboMWM** [comment]
Should be implemented in beta release.

**Comment by NullCase** [comment]
I'm sorry RoboMWM, it looks like you've already added bids?

Haven't tested this yet.

**Comment by RoboMWM** [comment]
Yes bidding should be implemented.

**Comment by RoboMWM** [comment]
If there's an issue either create a new one or reopen this one.

**Comment by NullCase** [comment]
It looks like sending that payment last weekend (ish?) was a good idea. Pending a test (will do tomorrow), it sounds like we're done with step 1.

**Comment by NullCase** [comment]
Hi @RoboMWM 

Bid testing:

- Created new auction. Price of 10000.
- Right click sign. No response. Nothing in console.
- For completeness, checked auctions.data and there are no bids listed under bids:[]


I'm sorry Robo, how do I reopen an issue?

**Comment by RoboMWM** [comment]
No reopen issue button for you? Huh.
