### ISSUE TITLE
Claim remains in list after being transfered to admin claim (until relog)

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#25]
Test: 
- create auction, type /claimlist, observe that auctioned claim is still listed. 
- This produces a negative claimblock balance (temporarily - see workaround). 
- The negative balance is a good sign because your plugin is deducting the correct amount of claim blocks

Expected behavior: 
- auctioned claim is no longer listed in the player's /claimlist.

Workaround: relogging fixes /claimlist so the claim is no longer showing incorrectly.

Extra Notes: 
Something like this happens with GPRealEstate too. When a player purchases a claim it will show twice on their claimlist until they relog. So, however this gets fixed perhaps it can be useful later on when I fund a round of development on GPRealEstate.

**Comment by RoboMWM** [comment]
Hmm, would this be because of ClaimsListClassifier? I'm guessing because the old claim is invalidated in datastore but still present, I guess? Hmm....

**Comment by NullCase** [comment]
It sounds like removing CLC and testing with GPR / GPA could answer the first question.

How about I try that on next release?

**Comment by NullCase** [comment]
Tested without Classifier. Claims remain as described until re-logging.

**Comment by RoboMWM** [comment]
Try transferring a claim with just GP

**Comment by NullCase** [comment]
Using /giveclaim the claim shows up right away. Is there another way you wanted me to test?

Here are the steps:
 - Created an admin claim (that is on no one's claim list). 
 - Did /giveclaim NullCase. 
 - Then checked /claimlist again.
 - Claim appeared in the claim list right away, which is nice.

**Comment by RoboMWM** [comment]
I guess /giveclaim is an alias for /transferclaim. Alright. Will check what GP does when performing a transfer.

**Comment by RoboMWM** [comment]
So there's a method in DataStore named "changeOwners" but it probably was never used because it had an exception in its method signature, but the exception class was never public so nobody could actually use it. I just committed a change to GP to make this public, so you'll have to use a [dev build of GP](https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/23145319/artifacts) until an official update is released.

**Comment by RoboMWM** [comment]
Seems all it does besides what I do is update the internal claims held in the playerdata. Big_Scary has a lot of caching going on...
