### ISSUE TITLE
Returned claims (when auction ends without bidder) do not appear in /claimlist until relog

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#26]
This bug seems related to #25 

Test:
- set default auction length to 1 hour (something short.
- create auction. 
- let auction end without bids.
- claim blocks are returned to claim owner (good!)
- claim is returned to owner (owner can place blocks, manage the claim.

the bug is just this: the claim does not appear in /claimlist. This means the player will have more claim blocks available to spend than they really ought to have. They can either sell the claim blocks OR claim more land & then relog. This means they own more land than they actually have.

**Comment by NullCase** [comment]
Tested without ClaimlistClassifier. Bug remains as described.

**Comment by RoboMWM** [comment]
Same as #25
