### ISSUE TITLE
General Updates - Closed when GPAuctions is completed with autoAuctions.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#27]
Hi RoboMWM,

The first 8 minutes of this video (below) were requested by players on the server. They requested a "show me" approach and I have been posting video updates of our progress. I'm getting regular feedback from them. 

This issue can close when we release the first version. 

The first 8 minutes contain details pertaining to my thoughts on our progress so far.

https://www.twitch.tv/videos/385635488

**Comment by NullCase** [comment]
OK, just found the latest release. Will test later or tomorrow. Thanks!

**Comment by NullCase** [comment]
I don't know if you want these videos. What do you think?

Here's ~20 minutes of testing. https://www.twitch.tv/videos/388771492

**Comment by RoboMWM** [comment]
Videos are fine, tho twitch's interface is a bit hard to use, haven't found a good app that allows me to do 2x speed like I can with the MyTube app for YouTube. Of course I prefer issues for any bug reports or suggestions so I can quickly review whenever I have time.

**Comment by NullCase** [comment]
When you have time, yeah. It seems like GitHub's issue system is a far better way to get work done.

I also prefer to use issues to provide quick and clear info. This will continue.

**Comment by NullCase** [comment]
the .data file can accumulate many bids quite quickly. which is fantastic.

It seems like even one auction could see bids coming in with thousands in a few minutes.

At what point do you think that becomes a problem?

So far it looks like GPA is causing ~no lag. Which is good.

But what about some kind of rate limiter?

**Comment by RoboMWM** [comment]
Auctions are saved asynchronously, so there shouldn't be any issues.

**Comment by NullCase** [comment]
Next release I can start clearing those test cases. We're putting it live on a second server.

**Comment by NullCase** [comment]
@RoboMWM it looks like the 4 phases are done.

All I see left is some polish and AutoAuctions.

It seems like AutoAuctions are being forgotten a little. This part of the project is very important.

I'd like to discuss this a little to make sure we're on the same page. Please keep in mind that I wish to treat you fairly and so if I mess that up we can go back to put it right.

Do you feel like AutoAuctions is beyond the original description of this work?

**Comment by RoboMWM** [comment]
No, I'm aware the auction on expiration is part of the plugin. It's just the last thing to implement since it requires the auction system and features to be working and implemented first.

**Comment by NullCase** [comment]
The last thing. OK, it sounds like building the auction system first and then automating it was the best way to go.

**Comment by NullCase** [comment]
Hi RoboMWM, it seems like you're really busy. Still just in case we end up losing an opportunity to test online, here's a what's happening now.

Our test server will be online for about 3 more weeks. During that time its easier to test online with help from the players. Do you think that will be a problem?

**Comment by NullCase** [comment]
OK, i see the releases. Will test tomorrow. Thanks RoboMWM

**Comment by NullCase** [comment]
@RoboMWM Your initial compensation for this project was $115 which was raised to $131 when some extra items came up (gpacancel, other particulars like formatting stuff)

 So far you've received the 4 payments of $15 for each of the 4 phases and the remaining $71 is still set to be provided upon final completion (after some bug testing).

It seems like things are going really well, but there may also be some challenges ahead. For example, my test server being available for just a few more weeks.

What if we get out in front this time? Put some money up that covers those challenges.

If you accept, I will increase my offer to $139 total for Auctions. You will receive a final payment of $79 upon completion.

How does that sound?

**Comment by NullCase** [comment]
Thanks for the quick turn around. Still testing now with more results to follow.

**Comment by NullCase** [comment]
Now testing whether claim blocks are credited to the auction winner to cover the cost of the land claim.

**Comment by NullCase** [comment]
OK, done testing for today. Thanks @RoboMWM

**Comment by NullCase** [comment]
Hi @RoboMWM 

It looks like we're almost done. How's your schedule look for Auctions over the next few days?

I want to complete this work and get you paid.

Polishing up the remaining bugs and including a log file gets me a finished product.

We can also talk about 1.2 because user specified duration is totally not from the original design of Auctions. You will be paid the amount listed and this amount does not include #18 

That said, I think it's a great addition which there will be funding for. I think the players are going to love GPAuctions. And that they will want the option to define their own auction duration. So we can come back to it with more funding.

Do you think we can complete this work with logs included and come back to _user specified auction duration_ as a future paid item for development?

**Comment by RoboMWM** [comment]
Sounds fine to me

**Comment by NullCase** [comment]
What do you need at this point to get from here to completion?

**Comment by RoboMWM** [comment]
Everything in the 1.2 milestone, as far as I'm aware.

**Comment by NullCase** [comment]
Hi @RoboMWM Thanks for the latest update.

It looks like the last few updates have failed (to compile?).

Is there anything you need me to do?

**Comment by RoboMWM** [comment]
Thanks, I guess I never opened the MakeBidListener class after refactoring the Bids collection so Intellij never let me know that class couldn't be compiled.

**Comment by NullCase** [comment]
It looks fixed from here too. Thanks Robo.

**Comment by NullCase** [comment]
Hi @RoboMWM Final payment sent. It looks good.

https://github.com/RoboMWM/GPAuctions/issues/48 is the only item left.

**Comment by NullCase** [comment]
@RoboMWM OK, big question. What's one thing that worries you about GPAuctions?

**Comment by RoboMWM** [comment]
Worries me? In what regard?

**Comment by NullCase** [comment]
it seems like you're not worried about it :)

Still, anything that felt a bit rushed or wasn't tested. Stuff like that.

**Comment by RoboMWM** [comment]
Well I haven't tested this at all especially since I don't foresee myself using this anytime in the near future. And I don't think anything feels rushed. Maybe a little bit of refactoring could be done due to the feature requests that came up along the way (namely performing actions on auction close based on if the auctioned claim has an expired owner, for lack of a better term), but other than that I think it's fine. You've been patient and helpful with the testing along with creating and labeling issues, so no issues there on that either c:

**Comment by NullCase** [comment]
OK, it sounds like adding new stuff might change how the current stuff is done. Definitely a question for when that day comes. That's great.

No issues with QA/testing etc.. Great!

It looks like we've been doing work for over a year, which is crazy. Because the claim block duplication glitch was in December 2017.

That was when players incurred a negative claim block balance when buying land producing a dupe on relog (caused by GPRE but solved in GP nevertheless). 

Not bad RoboMWM! This is definitely the biggest thing so far.

**Comment by NullCase** [comment]
It looks like our last (first) release was a couple months ago. 

Idk how this stuff works. How hard is it to post a release on GitHub?

Because I'd like people to use and try to break Auctions a lot. So far my players haven't found a way to break it.

**Comment by RoboMWM** [comment]
If you have a bukkitdev account I can give you access to the project page to create releases.

**Comment by NullCase** [comment]
Going to push the log to 1.3 and close this. Because then there's no loose ends to check on. Closing this up just lets me move on to other projects without anything hanging around to interrupt.

If you decide to release https://github.com/RoboMWM/GPAuctions/issues/48 in the meantime that's totally cool. I'll test & provide feedback in due course.

Really happy with Auctions.

**Comment by RoboMWM** [comment]
Ok cool. My schedule changed this week and I've been exhausted so haven't had time to start working on the logging feature. I'll try to get to it soon.

**Comment by NullCase** [comment]
Exhausted. That's a sign. Killing the coder sounds like a pretty bad strategy for getting 1.3 done later.

We'll come back to logs in 1.3.

**Comment by RoboMWM** [comment]
FYI, not exhausted from this, but from my aforementioned schedule change.
