### ISSUE TITLE
Broadcast claim is on auction, starting bid, sign coordinates.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#29]
I'm sorry it looks like a really good time for a for break this minute but the players have reminded me about this feature in the original design notes. It seems like a good idea to post this issue before forgetting.

**When an Auction is created:**

/broadcast [&6GPAuctions&f] &bAn auction has been created at &a[Auction Coordinates]&b. Bidding will start at &a[startingBid]&b.

**Comment by RoboMWM** [comment]
It's fine, no need to worry about me being overloaded because the issue count number has increased lol c:

**Comment by NullCase** [comment]
Increase issue count lol. I don't know why, but that part seems kind of enjoyable.

**Comment by NullCase** [comment]
What do you think of using the Sign coords to tell people where to go?

**Comment by RoboMWM** [comment]
> What do you think of using the Sign coords to tell people where to go?

Makes logical sense, since that's stored in the Auction object anyways (so it can be updated).
