### ISSUE TITLE
gpacanceled claim remains admin claimed

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#31]
Test: make auction, cancel auction as auction owner, use stick on claim / try to interact with the claim.

Results: auction remains admin claimed.

Expected results: auction returned to auctioneer/claim owner.

**Comment by NullCase** [comment]
possibly related.

- auction remains in the .data file after /gpacancel.
- unable to create new auction on location.
- attempting /gpacancel results in "[GPAuctions] This is not your auction....

**Comment by NullCase** [comment]
oddly, it worked the second time. I'll try & sort that out.

**Comment by NullCase** [comment]
this might come up again but I couldn't replicate the problem.

**Comment by RoboMWM** [comment]
I forgot to call saveClaim when changing the owner for this method. So it would revert to an admin claim on server restart/reload unless something caused the claim to save before that happens. Since I now use changeClaimOwner this should no longer be an issue.
