### ISSUE TITLE
When auction ends.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#32]
When the auction ends
- Update Sign to replace the "Auction" line with: 
&2Auction Closed

- Mail the auctioneer and winner, where applicable.

**When auction has bidders:**

/mail send [auctioneer] &f[&6GPAuctions&f] &a[Player name] &bhas won your auction at &a[coordinates] &b. The final bid was &a[final bid amount].
/mail send [winner] &f[&6GPAuctions&f] &bYou have won the Auction! &a[final bid amount]&b has been deducted from your account balance. Your new property at &a[coordinates]&b has been transferred into your care.
broadcast &f[&6GPAuctions&f] &bThe auction at &a[coordinates] &bhas closed. The auction winner is &a[winner]&b with a final bid of &a[final bid amount].

**When auction ends without bidders.**

/mail send [auctioneer] &f[&6GPAuctions&f] &bYour auction has closed without bidders. The claim has been returned to you.

---

For AutoAuctions without bidders:

/mail send [auctioneer] &f[&6GPAuctions&f] &bYour auction at &a[coordinates]&b has closed without bidders. The claim has expired due to inactivity.

**Comment by RoboMWM** [comment]
I assumed

> &a[final bid amount] has

should be

> &a[final bid amount]&b has

**Comment by RoboMWM** [comment]
Same with [winner] in broadcast

**Comment by RoboMWM** [comment]
Do you want auctions started due to claim inactivity to send a message to the owner? The player would probably be bombarded with a ton of messages.

**Comment by NullCase** [comment]
Quite late here, please excuse the poor response.

Auctions started due to player inactivity... in that case no mail/message about it starting.

It seems like CLC will still mail them that their claims have expired. And after the auctions close they'll get mail. This still might be a lot of mail for some players. I'm not worried about it because those cases will be rare.

**Comment by NullCase** [comment]
> Same with [winner] in broadcast

Right on both counts. The post is updated with those changes.

Also updated to add &f at the start of the mail/broadcasts/messages to future proof against server-side formatting in other plugins.

Also removed some extra spaces. Again, my mess up.

**Comment by RoboMWM** [comment]
Instead of adding a field to tag an auction as one automatically created, I'll just check if the owner hasn't logged on since the specified expiration time in the GP config... how does this sound?

**Comment by RoboMWM** [comment]
Well I did that

**Comment by RoboMWM** [comment]
I guess github doesn't handle continuous tense yet.

**Comment by RoboMWM** [comment]
I guess github can't handle continuous tense.
