### ISSUE TITLE
Old auction sign can be used for bidding if a new auction sign is created

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#35]
Test: 

- Create auction. Cancel auction (Sign updates to say canceled).
- create new auction with new sign. (keeping old sign).
- right click old sign and it will bid on new auction.

**Comment by NullCase** [comment]
It seems like this is only a problem where players are 'tricked' into bidding at a price which is not the next bid. A canceled sign (for instance) may display a price which is well below the next bid.

**Comment by NullCase** [comment]
One simple fix would be to break the sign when an auction is canceled. 

This would defeat the purpose of updating the sign to "Auction Canceled" but if its the easiest route then let's do it. 

After all, GPRealEstate already does a similar thing when an auction is purchased.

Edit: Although, perhaps the 2nd line can be used as a check. Because it seems like the sign after an auction concludes can also be used (just a guess).

What do you think?

**Comment by RoboMWM** [comment]
Hmm, I guess I should check if the right-clicked sign matches the one stored in the auction since we are using signs to update the auction status.
