### ISSUE TITLE
Automatically create auction for expired claims

### ISSUE THREAD

**Issue by RoboMWM** [RoboMWM/GPAuctions#4]
- Figure out where to place sign (probably near /trapped location??)

- If auction fails, abandon claim.

**Comment by NullCase** [comment]
This is the most important part of the project. By far.

Where to place the sign...

It seems like something 'constant' with a K will be the easiest for players to find.

What about starting with the claim's "Lesser Boundary Corner" (GP's claim data)?

I don't know what kind of algorithm could place it above ground near that corner.... Interesting problem.

How can I help?

**Comment by RoboMWM** [comment]
Corner would work. It's easy to find the highest block above ground. Might be an issue for nether claims though.

**Comment by NullCase** [comment]
It seems like signs would be placed on the ceiling for nether claims. Do I have that right?

For us that's no problem.

What if all Y is solid blocks from 0 to 256?

**Comment by RoboMWM** [comment]
> It seems like signs would be placed on the ceiling for nether claims. Do I have that right?

Yes.

> What if all Y is solid blocks from 0 to 256?

If that's the case, it won't be placed. So I could try placing adjacent to it, increasing x or z coordinate.

**Comment by NullCase** [comment]
That sounds perfect to me.

What's next up?

**Comment by RoboMWM** [comment]
> What's next up?

Not sure. You can edit the issue if you wish to clarify the tasks. I'll try to get some more stuff done today.

**Comment by RoboMWM** [comment]
Oh, no wonder why you couldn't see a button to reopen issues and whatnot. You haven't accepted the invitation yet. https://github.com/RoboMWM/GPAuctions/invitations

**Comment by NullCase** [comment]
> Not sure. 

In your list of 4 steps, bids is the last part of step one. https://github.com/RoboMWM/GPAuctions/issues/2

Then displaying Auction info is step 2.https://github.com/RoboMWM/GPAuctions/issues/17

That sounds like a good route.

**Comment by RoboMWM** [comment]
Reopen if there are issues. Probably would've been nice to keep all "autoauction"-related stuff here instead of spread out with other issues (had to bounce between a few for messages etc.) but it's ok.
