### ISSUE TITLE
Existing claims not able to create auction until 'given' to the player.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#41]
Test: Find claims that already exist, try to auction them. Sometimes it doesn't work. Use /giveclaim [same player] and try again. It works.

Expected: Auction works on pre-existing claims without giving them to the player.

About 12 minutes into this video.
https://www.twitch.tv/videos/398873242

**Comment by NullCase** [comment]
Weird one. Another claim which behaved the same way. I created an auction sign

[ac]
1000

Didn't update, as expected but not preferred.

Then I placed a sign in the same location.
Then I resized the claim.
That created an auction except the price line was blank so it calculated the price based on the claim blocks.

**Comment by NullCase** [comment]
I also tested by creating an Auction in the claim and then creating a [Real Estate] sign. The Real Estate sign works.

This might be related to another issue (not listed yet) where closed auctions that have already sent mail/broadcasts are re-sending on server restart. **Edit:** on server restarting (again to test this out) the mail was not re-sent. That might be a 1-off thing.

**Comment by NullCase** [comment]
OK, it looks like claims which previously had an auction cannot be auctioned again after the auction ends.


Edit: For completeness, some other claims also show this behavior (for example, a claim which had existed for >8 months was not able to be auctioned until it was given to them again).

**Comment by RoboMWM** [comment]
Weird, will need some debugging here. Auctions are removed if they have ended or are canceled. However this remove operation wasn't being saved, so if no other auction was added (triggering a save), and server restarts, then the auctions would be re-added into the collection. (The auction end checker only checks every minute, so would need to wait a minute after server start for them to be removed again.)

**Comment by NullCase** [comment]
It looks like this one is still around. It seems like claims which have been around for a while cannot create an auction.

Test: Stopped server, added GPAuctions, started server. Tried to create an Auction in an existing claim.
Result: Auction not created.
Expected: Auction created.

**Console:**

```
05.04 04:13:50 [Server] INFO [GriefPrevention] NullCase placed a sign @ world: x-59, z9;[ac];157999999
05.04 04:13:50 [Server] INFO [GPAuctions] SignChangeEvent called
05.04 04:13:50 [Server] INFO [GPAuctions] Line 1 matched sign
05.04 04:13:50 [Server] INFO [GPAuctions] Claim found
05.04 04:13:59 [Server] INFO [GPAuctions] Sign clicked
05.04 04:14:07 [Server] INFO NullCase issued server command: /giveclaim nullcase
05.04 04:14:07 [Server] INFO [GriefPrevention] NullCase transferred a claim at world: x-81, z5 to NullCase.
05.04 04:14:16 [Server] INFO [GriefPrevention] NullCase placed a sign @ world: x-59, z9;[ac];150999999
05.04 04:14:16 [Server] INFO [GPAuctions] SignChangeEvent called
05.04 04:14:16 [Server] INFO [GPAuctions] Line 1 matched sign
05.04 04:14:16 [Server] INFO [GPAuctions] Claim found
05.04 04:14:16 [Server] INFO [GPAuctions] Set starting bid to 1.50999999E8
05.04 04:14:16 [Server] INFO [GPAuctions] addAuction called
05.04 04:14:16 [Server] INFO [GPAuctions] Pre-existing auction does not exist.
05.04 04:14:16 [Server] INFO [GPAuctions] Set claim owner to null (admin claim) and cleared trustlist
05.04 04:14:16 [Server] INFO [GPAuctions] Deducted 884 bonus blocks from player ac3b0963-75bd-44d2-b6ad-12efa76985cc
05.04 04:14:16 [Server] INFO [GPAuctions] Starting to save auctions
05.04 04:14:16 [Server] INFO [GPAuctions] sign location save Location{world=CraftWorld{name=world},x=-59.0,y=68.0,z=9.0,pitch=0.0,yaw=0.0}
05.04 04:14:16 [Server] INFO [GPAuctions] Saved auctions to file.
05.04 04:14:16 [Server] INFO [GPAuctions] Adding auction with ID 2405
05.04 04:14:16 [Server] INFO [GPAuctions] Auction started. Claim ID: 2405 endTime: 1555056856646 startingBid: 1.50999999E8
05.04 04:14:16 [Server] INFO CONSOLE issued server command: /broadcast [GPAuctions] An auction has been created at -59, 9. Bidding will start at 1.50999999E8.
```

**Comment by RoboMWM** [comment]
Thanks, log messages were useful.
