### ISSUE TITLE
For AutoAuctions, destroy the auction sign on Auction Close.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#45]
Presently, the auction sign is recoverable when broken.

I would like those AutoAuction signs to vanish when they are broken.

Note: The ones placed by players are legitimate signs and I want those to be recovered when broken, but AutoAuction signs are kinda cheaty because they're created out of thin air.

**Comment by RoboMWM** [comment]
Would it be better to destroy the auction sign after the auction closes? Otherwise I'd have to store locations of auto-generated signs and await a break event to delete the corresponding drop.

**Comment by NullCase** [comment]
After it closes. Yep if that's easier let's do that.

**Comment by NullCase** [comment]
Sign not destroyed on AutoAuction close:

**test:** two AutoAuctions: one with bidders, one without. Wait for both to close.
**result:** neither sign destroyed.
**expected:** both signs destroyed.

**Comment by NullCase** [comment]
idk, just had a thought.

do you think this sign placement function will break in 1.14? because of the new signs.

**Comment by RoboMWM** [comment]
There's more new signs in 1.14?

I don't see any reason why the `Sign` blockstate would change though.

Anyways, I guess changing the type in the blockstate isn't a valid way to remove a block. I just released a commit that changes the block type the standard way.

**Comment by NullCase** [comment]
Fixed.
