### ISSUE TITLE
Message replacement for "Auction started with starting bid price at..."

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#5]
Currently:
Auction started with starting bid price at 884.0

Request:
[&6GPAuctions&f] &bAuction has started with starting bid of &a844

Format matches GPRealEstate

**Comment by RoboMWM** [comment]
Would economy formatting be preferred? e.g. …`bid of &a$844`

**Comment by NullCase** [comment]
I think it's OK without. That's how GPRealEstate works and nobody's ever complained.

And, it looks like a shorter number will help because of large values on a sign with limited space.

$1,000,000.00 vs 1000000

Shorter.

Edit: I guess for the command message space isn't an issue, but still. I think its OK as requested.

**Comment by NullCase** [comment]
It looks like I can test tomorrow, around this time. If there is something ready to check.
