### ISSUE TITLE
AutoAuction sign placement

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#50]
This was a funny one. Ty for that.

![2019-03-22_15 01 30](https://user-images.githubusercontent.com/32785664/54846977-807c5680-4cb3-11e9-9bc0-164e816edd87.png)

Test: Create claim, give claim to player who's claims will expire, wait.
Result: Auction sign placed underground, replacing a block. Very funny.
Expected: Auction sign placed on claim corner. Boring but correct.

**Comment by RoboMWM** [comment]
It looks like there's water above, is that so?

~~Not sure why Bukkit is providing inconsistent results for World#getHighestBlockYAt~~ turns out instead of removing the 1 + y, I just removed it altogether and didn't use getHighestBlockYAt at all. Oops.

**Comment by NullCase** [comment]
Well, i don't know if it's helpful to explain a bug you've already addressed.

Still, it looks pretty simple after some more testing. 

The sign is being placed at the lowest block within the claim at that corner. For surface claims it was 5 blocks underground. For claims near bedrock the sign placed at the bottom of the world, removing bedrock. And so, creating the apparent inconsistency.
