### ISSUE TITLE
Adjust auction info display rate when using Shift+Click

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#51]
Test: shift+right click an auction sign.
Result: Auction info is rapidly displayed but always appears at least twice. Up to 6x per second.
Expected: Displayed once per click. Perhaps 1x per second maximum?

Notes: It's really fast & light weight so I don't see the rate causing lag. Just from an aesthetic view, not filling up players chat.

![2019-03-22_16 53 01](https://user-images.githubusercontent.com/32785664/54852330-f3d99480-4cc2-11e9-907f-da99e489008c.png)

**Comment by RoboMWM** [comment]
Client-side issue is my guess. If your mouse is faulty or if you hold right-click a tad too long it'll fire repeatedly.

**Comment by NullCase** [comment]
OK, let's skip it and come back to this after launch.
