### ISSUE TITLE
Players with multiple claims create only one AutoAuction at a time.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#53]
This seems good. Less chat spam. Players have a moment to sort out what's on auction. I like one AutoAuction being created at once.

Right now it only means that players receive lots of mail from ClaimClassifier. With each AutoAuction created.

Do you think that's caused by Auctions?

**Comment by RoboMWM** [comment]
What're you asking? Not sure what the question is here along with the wontfix label

**Comment by NullCase** [comment]
Not sure. OK.

At the moment when a player's claims expire their claims go on auction but just one at a time (one per check). This looks good to me. I don't want that 'fixed' (So, wontfix label).

The only down side is that every time a player's claim goes on Auction they receive mail that their claims have expired due to inactivity (which is from ClaimClassifier, claimexpire delay). Of course, I want that mail sent but once would be fine. At the moment players receive one mail per claim.

My question is do you think the repeated mail is caused by Auctions or no?

**Comment by RoboMWM** [comment]
Yes, as per https://github.com/RoboMWM/GPAuctions/issues/32#issuecomment-473784228 I ignored this issue.
