### ISSUE TITLE
auctions.data not created in 49931c54

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#62]
I don't know how to explain this best so here is what I did.

- Downloaded the latest version: [49931c54](https://ci.appveyor.com/project/RoboMWM39862/gpauctions/builds/28098665/artifacts)
- Deleted the old auctions.data file.
- Started the server.
- Prepared a nice screenshot.

![after deleting the old file no new auctions dot data file where is the data saved](https://user-images.githubusercontent.com/32785664/66787273-0b6fa900-eeb1-11e9-9715-a1083503291e.png)

It looks like auctions are being created just fine, but it doesn't seem that they are saved anywhere. Because I restarted the server to double check and see if they are retrieved (in case you were saving them another place) but no auctions are found on restart.

**Comment by NullCase** [comment]
will check back tomorrow to test again. Thanks RoboMWM!

**Comment by RoboMWM** [comment]
Thanks. I took a guess at using SynchronousQueue, expecting it to work like a lock and my guess was wrong. It works more like a mutex instead. Changed the implementation to use an actual Lock - so it should work now.

https://ci.appveyor.com/project/RoboMWM39862/gpauctions/builds/28114642/artifacts

**Comment by NullCase** [comment]
this is fixed.
