### ISSUE TITLE
config option: debug messages in console.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#65]
`[GPAuctions] Sign clicked` shows up a lot. Is now a bad time to add this config option to turn off debug messages in the console? Because I've just posted https://github.com/RoboMWM/GPAuctions/issues/64 and it seems like they're at least related in concept.

In case I'm not quite correct, please check.... but it looks like this was the version where debug messages were added to the console:

https://ci.appveyor.com/project/RoboMWM39862/gpauctions/builds/23175931

**Comment by RoboMWM** [comment]
Hmm, do I not have a `debug` config option?

**Comment by RoboMWM** [comment]
oh I guess I do not. Whoops.
