### ISSUE TITLE
ClaimBlocks not returned when AutoAuction closes without bidders.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#66]
Well, bad news. Found a really terrible bug.

Observed: When AutoAuctions close without bidders, the claim blocks are not being returned to players.

Expected: Return ClaimBlocks when auctions close without bidders.

It's late, and I shouldn't really be working on this now but found this bug. Don't want to forget.

edit: just to restate in case its unclear.

AutoAuction starts, claim blocks deducted from balance. This is all great.
AutoAuction closes, claim blocks should be returned if there's no bidders.

**Comment by NullCase** [comment]
Player created auctions don't have this bug. Tested it this morning.

Just in case I'll test this again later, in case player created auctions w/o bidders return double claim blocks.

After it's fixed I'll have to comb over the logs to correct balances.

**Comment by NullCase** [comment]
OK, how much $ to solve this one @RoboMWM ?

**Comment by RoboMWM** [comment]
Oh, so it's just the automatically-created ones. Interesting. Will take a look by this weekend.

**Comment by NullCase** [comment]
Just automatic ones, yeah.

I don't know why, but it seems like the reason will be kind of obvious. Like if the "give back claim after auction closes without bidders" code has the "refund blocks" code inside it.

So the refund doesn't execute because the claim is meant to expire for autoauctions without bidders.

**Comment by RoboMWM** [comment]
> So the refund doesn't execute because the claim is meant to expire for autoauctions without bidders.

That's probably what's happening.

**Comment by RoboMWM** [comment]
https://ci.appveyor.com/project/RoboMWM39862/gpauctions/builds/28366904/artifacts

**Comment by NullCase** [comment]
will test tmr.

**Comment by NullCase** [comment]
tested and it works as intended. payment sent. thanks @RoboMWM
