### ISSUE TITLE
Sign position replacing claim corner block

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#67]
Hi @RoboMWM,

It looks like I've found a bug and funding is available to fix it.

Auction signs are replacing a block in the corner. It looks like the Y position is off by one.

![2020-04-07_19 55 18](https://user-images.githubusercontent.com/32785664/78730118-e614a280-7909-11ea-8ef9-f50ae73ecbfe.png)

**Comment by NullCase** [comment]
This has existed for a while, but I wanted more information. At first I thought it was related to walls/fences.
![2020-02-18_16 44 03](https://user-images.githubusercontent.com/32785664/78730282-54596500-790a-11ea-817b-6ef49adaf927.png)
![2020-02-18_16 43 54](https://user-images.githubusercontent.com/32785664/78730286-57545580-790a-11ea-8fca-71323171c5a1.png)

**Comment by RoboMWM** [comment]
This happened because spigot modified the getHighestBlock method.

**Comment by RoboMWM** [comment]
https://github.com/AcmeProject/WildernessTp/issues/60#issuecomment-587072723

> So the change was made here https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/807a677e9a59929e27ac1991c3fa1cf6a2ec0f4d

**Comment by NullCase** [comment]
spigot changed their method. OK, great looks like you've found it.

Does this mean spigot has a bug? Because it looks like they wanted the change.

I don't know if you want to fix this for Auctions, but I'm still interested to.

**Comment by RoboMWM** [comment]
yes I can fix. Just forgot to yesterday

**Comment by NullCase** [comment]
Tested and it looks good. $ sent, thanks @RoboMWM
