### ISSUE TITLE
If the auction sign breaks, cancel the auction.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#69]
You'll think I wasted some time and ignored your solution. Because I want to try a different approach. I'm pretty annoying sometimes, sorry.

If this works then it's a robust fallback solution when Mojang invents new block behavior to break signs in the future. It might be really simple too.

--------------

**Request: If the auction sign breaks, cancel the auction.**

I don't know how this works in code, but it seems like #43 uses 'broken by player' as the trigger.

https://github.com/RoboMWM/GPAuctions/commit/e63c901b952d64e3c723a564c57ba0e359da4ffd

How do we add an 'environmental breaks' event as a second trigger for that?

Things i will test:
- Auction canceled in data file.
- Claim returned to the former owner.
- Claim blocks returned to the former owner.
- Check that claim blocks are not refunded twice (in case it somehow runs for both break events).

**Comment by RoboMWM** [comment]
> then it's a robust fallback solution when Mojang invents new block behavior to break signs in the future. 

Well if they do introduce these, it'll likely occur in a different event that'll need to be handled. 

Anyways, iirc, signs are pretty resilient - they only require that the block they're attached to remains in place. So... I believe the event fired is the BlockPhysicsEvent for this scenario. This event is called a lot for other events but the check for a sign should be somewhat cheap.

**Comment by RoboMWM** [comment]
> You'll think I wasted some time and ignored your solution. Because I want to try a different approach. 

Nope that's perfectly fine, as the user you're the one defining the "what"

**Comment by NullCase** [comment]
Somewhat cheap. That sounds a bit like CheaperPhysicsEvent which Phoenix616 coded up. I don't know if that's worth mentioning. https://www.libertyminecraft.com/cheaperphysicsevent-by-phoenix616/

**Comment by NullCase** [comment]
Yeah, he switched to BlockDestroyEvent listeners which I don't know if that can work here.

**Comment by RoboMWM** [comment]
Interesting, a Paper event. Ok that's cool.

**Comment by RoboMWM** [comment]
Please verify that the feature works as expected when the sign is broken by a player. I tried asking if `BlockDestroyEvent` also covers when a player breaks a block (i.e. fired alongside `BlockBreakEvent`) but haven't received a clear response...

**Comment by NullCase** [comment]
To verify, i ran a few tests. Main result, to your question: "player breaks" does not appear to be covered by the destroy event.

------------
Test: as OP, created auction, broke the auction sign manually.
Result: Auction not canceled. No errors in console.

Test: as player, created auction. Broke sign as OP (since it's admin claimed).
Result: Auction not canceled. No errors in console.

Test: as player, created auction. Canceled auction using /gpacancel
Reason: Just for completeness, I expected this to work.
Result: Auction DID cancel.

Test: as player, created auction. as OP, broke block underneath to destroy sign.
Reason: Completeness, I expected this to work.
Result: Auction canceled exactly as intended. Claim blocks returned, claim returned. All 100%.

**Comment by RoboMWM** [comment]
Ok thanks - so their javadocs are indeed unclear and do _not_ cover the case where the player breaks the block...
