### ISSUE TITLE
Add location.getWorld().getName() to Auction Creation's Broadcast

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#70]
This update is intended to match our [recent update to GPR](https://github.com/RoboMWM/GPRealEstate/commit/ccb60f6733cec0b3e0239388cbc855ca3f3094e0) with GPAuctions.

I don't know the best way to add more info here... but this is a summary:

- AutoAuction or Auction is created.
- The offer is broadcast to the world.
- Right now, there's no world name included.
- GPR includes the world name, and that's what I'd like GPAuctions to do.

**Comment by NullCase** [comment]
Good news first: As you expected, the other mail/broadcasts ARE showing world names.

Bad news: The display format is different. Did I request the wrong thing?

Image below shows a real estate and Auction broadcast, to show the difference.

![2020-05-20_19 44 28](https://user-images.githubusercontent.com/32785664/82508200-52222300-9ad2-11ea-8064-d88151bf62bd.png)

**Comment by RoboMWM** [comment]
Oops, forgot to `getName` after `getWorld`.

**Comment by NullCase** [comment]
@RoboMWM It sounds like this will cover it but will test and send $$, hopefully tonight but definitely by tomorrow.

What do you think about chipping away at GPAuctions 1.3 in small updates like this one?

Next month I'm focusing on studies for the first week or 2, at least. Then I get to decide what to build next for LMC.

**Comment by NullCase** [comment]
Ah! found one thing:

See how the worl
d_nether part gets cut off, put on the next line. How do we fix that?

![2020-05-21_17 07 45](https://user-images.githubusercontent.com/32785664/82606778-a33f1f00-9b85-11ea-935c-441bf2f3ac1c.png)

**Comment by RoboMWM** [comment]
I believe this is a client-side thing. I think Bukkit does have some fixed form of normalization (if that's the right term) for line wrapping but it's not perfect, and sometimes does result in things like this.

**Comment by RoboMWM** [comment]
I think I tried looking this up once before but I don't recall if I ever did find anything on this line wrapping that bukkit has kinda appears to have built-in

**Comment by RoboMWM** [comment]
That, or it's totally on the client - I don't really know or recall.

**Comment by NullCase** [comment]
What if we just add a word.

Instead of "An auction has been created..."
Change to "A land claim auction has been created..."

And then it looks fine?

**Comment by NullCase** [comment]
because for GPR, i dont know if a string (is that it) is handled differently, but it seems like that part of the broadcast wraps correctly.

**Comment by RoboMWM** [comment]
it just executes the broadcast command so the plugin responsible (EssentialsX) is performing the broadcast.

Again I think this is a server thing or a client thing, not a plugin thing. If you change the UI size/textbox settings it would probably change the wrapping.

**Comment by NullCase** [comment]
OK, let's just call this done. $ sent.

**Comment by NullCase** [comment]
I'll wait on feedback and see what people say. And think about solutions.

**Comment by RoboMWM** [comment]
Tried a singleplayer world, and indeed the chat client is automatically performing line wrapping.

**Comment by RoboMWM** [comment]
yea, must be a chat client thing. I know I see similar behaviors... but only on certain screens. Not on this one though.

![](https://i.imgur.com/qAj79dt.png)

**Comment by RoboMWM** [comment]
someone might be on to something - may have to do with chat color codes

**Comment by RoboMWM** [comment]
I'm not sure if a space between the code and the word will help, but I might as well attempt that

**Comment by NullCase** [comment]
Wow! thank you for working on this. I'll test & respond probably late today.

**Comment by RoboMWM** [comment]
Yea, I have a tendency to comment my thoughts on things when I read it, so if I happen to find or hear of more clues afterwards I'll follow up

**Comment by NullCase** [comment]
I was surprised because at first it sounded like you had given up on solving this problem.

**Comment by NullCase** [comment]
https://github.com/RoboMWM/GPAuctions/issues/73
