### ISSUE TITLE
Add location.getWorld().getName() to Auction Close Broadcast.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#71]
Same idea as in #70 

Currently, Auction close does not broadcast the world name.
Request: add the world name to match GPR's sale creation broadcast, to also match Auction creation broadcast.

**Comment by RoboMWM** [comment]
bf0e4ea5ae043dd0ae44cec88e5262c704d905c4 should cover all cases where the location is printed, therefore this feature is already completed.

**Comment by NullCase** [comment]
already covered yep.
