### ISSUE TITLE
Add location.getWorld().getName() to Auction close mail.

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#72]
Currently, player mail shares coordinates without the world name. Just like #71 and #70 I'd like to add the world name to player mail.

```
/mail send VernierYeti6335 [GPAuctions] You have won the Auction! 918.09 has been deducted from your account balance. Your new property at -1315, -2767 has been transferred into your care.
20.05 10:32:05 [Server] INFO Mail sent!
20.05 10:32:05 [Server] INFO CONSOLE issued server command: /mail send peaceful_sl [GPAuctions] VernierYeti6335 has won your auction at -1315, -2767 . The final bid was 918.09.
```

Just before the coords I'd like to put the world name, just as you added in GPR.

**Comment by RoboMWM** [comment]
bf0e4ea5ae043dd0ae44cec88e5262c704d905c4 should cover all cases where the location is printed, therefore this feature is already completed.

**Comment by NullCase** [comment]
like the other one, already covered. Thanks.
